// Curated KiwiSDR catalog for HamHawk's 'best receiver' auto-pick + antenna picker.
// Generated from the public KiwiSDR registry (kiwisdr.com/public via rx.linkfanel.net).
// snr = real reported SNR (dB, higher=clearer); score = antenna-quality heuristic.
// KiwiSDRs are wideband HF (0-30 MHz) so every node covers all HF bands; ranking is
// by signal quality + antenna + region, not coverage. Data is a point-in-time snapshot.
export interface KiwiCatalogEntry {
  url: string; name: string; loc: string; antenna: string;
  grid: string; lat: number; lon: number; region: string;
  snr: number; score: number; users_max: number;
}

export const KIWI_CATALOG: KiwiCatalogEntry[] = [
  {"url": "http://wessex.hopto.org:8075", "name": "Wessex Flydog - G8JNJ - 0-62MHz - South West UK", "loc": "South West England, UK", "antenna": "Terminated Delta Loop 20m sides", "grid": "", "lat": 50.809, "lon": -2.477, "region": "Europe", "snr": 48, "score": 2, "users_max": 4},
  {"url": "http://g8ure.ddns.net:8079", "name": "80m Dipole (17 to 20) | Chichester UK", "loc": "Chichester UK", "antenna": "80m Dipole", "grid": "IO90qu", "lat": 50.837, "lon": -0.651, "region": "Europe", "snr": 46, "score": 1, "users_max": 4},
  {"url": "http://g3sdr.com:8077", "name": "G3SDR, 0-32 MHz Kiwi 8077. Weston-super-Mare. Parallel dipol", "loc": "Weston-super-Mare, United Kingdom", "antenna": "Parallel dipoles for 160m, 80m, 60m & 40m. 5/8th Vertical with masthea", "grid": "IO81MI", "lat": 51.317, "lon": -2.95, "region": "Europe", "snr": 42, "score": 6, "users_max": 4},
  {"url": "http://sdr.autreradioautreculture.com:8073", "name": "AutreRadioAutreCulture 1 | TREMOLAT (24), FRANCE", "loc": "TREMOLAT (24), FRANCE", "antenna": "Mini-Whip dual FET 3,50m", "grid": "JN04ku", "lat": 44.869, "lon": 0.835, "region": "Europe", "snr": 41, "score": 1, "users_max": 2},
  {"url": "http://21115.proxy.kiwisdr.com", "name": "HB9BMR 0...30 MHz | Gurmels, Switzerland", "loc": "Gurmels, Switzerland", "antenna": "https://active-antenna.eu/ 2x1meter", "grid": "JN36nv", "lat": 46.892, "lon": 7.163, "region": "Europe", "snr": 40, "score": 1, "users_max": 4},
  {"url": "http://wessex.zapto.org:8074", "name": "Wessex KiWi V2 - G8JNJ - 0-30MHz - South West UK", "loc": "Wessex - KiwiSDR - G8JNJ - South West UK", "antenna": "(same as Wessex KiWi V1)", "grid": "IO80qr", "lat": 50.74, "lon": -2.64, "region": "Europe", "snr": 40, "score": 0, "users_max": 8},
  {"url": "http://oh1ct.sytes.net:8073", "name": "OH1CT - 160m dipole - Loppi, Finland", "loc": "Loppi, Finland", "antenna": "160m dipole", "grid": "kp20fq", "lat": 60.673, "lon": 24.475, "region": "Europe", "snr": 39, "score": 1, "users_max": 7},
  {"url": "http://21595.proxy.kiwisdr.com", "name": "80m Four Square looking NW | Wales, UK", "loc": "Wales, UK", "antenna": "80m four square looking NW", "grid": "IO82", "lat": 52.5, "lon": -3.5, "region": "Europe", "snr": 39, "score": 0, "users_max": 8},
  {"url": "http://sdr.ironstonerange.com:8073", "name": "███ 0-30 MHz SDR #1, VK5PH, Ironstone Range, South Australia", "loc": "Ironstone Range, South Australia", "antenna": "12m Duoconical Antenna", "grid": "PF95ja", "lat": -34.964, "lon": 138.762, "region": "Asia/Pacific", "snr": 37, "score": 0, "users_max": 4},
  {"url": "http://kiwisdr.tko.zlwan.net:8073", "name": "KiwiSDR at Taikorea Road | Palmerston North, New Zealand", "loc": "Palmerston North, New Zealand", "antenna": "40/80 Fan Dipole", "grid": "RE79qp", "lat": -40.36, "lon": 175.38, "region": "Asia/Pacific", "snr": 36, "score": 1, "users_max": 4},
  {"url": "http://n0bqv.proxy.kiwisdr.com", "name": "0-30 MHz SDR | [N0BQV] [Republic, Missouri. USA", "loc": "[N0BQV] [Republic, Missouri. USA", "antenna": "40-75 meter Inverted Vee, feed point @ 75 Feet, 23 Meters....Please ch", "grid": "EM37fd", "lat": 37.164, "lon": -93.571, "region": "North America", "snr": 36, "score": 0, "users_max": 7},
  {"url": "http://kiwisdr.areg.org.au:8073", "name": "2-30MHZ SDR #1, VK5ARG Remote Receiver Site | Near Tarlee, S", "loc": "Near Tarlee, South Australia", "antenna": "Broadband Monopole (\"J-Dart\")", "grid": "PF95JR", "lat": -34.274, "lon": 138.771, "region": "Asia/Pacific", "snr": 36, "score": 0, "users_max": 4},
  {"url": "http://hl5ntr-sdr.ddns.net:8073", "name": "0-30 MHz KIWI SDR( 8ch ), HL5NTR, Daegu_City Republic of Kor", "loc": "Dae_Gu City, South Korea", "antenna": "HF 85M Loop Antenna and 6M Band 6 Ele Yagi & 5/8 GP Antenna", "grid": "PM45HV01", "lat": 35.889, "lon": 128.575, "region": "Asia/Pacific", "snr": 35, "score": 5, "users_max": 8},
  {"url": "http://w3ilt.proxy.kiwisdr.com", "name": "Mark W3ILT | Fallentimber, PA USA", "loc": "Fallentimber, PA USA", "antenna": "625 foot Beverage NW", "grid": "FN00", "lat": 40.661, "lon": -78.511, "region": "North America", "snr": 35, "score": 3, "users_max": 8},
  {"url": "http://il38.ddns.net:8073", "name": "0-30 MHz SDR, EA8-DF4UE, Fuerteventura, Canary Islands", "loc": "Fuerteventura, Canary Islands", "antenna": "80/40/20/15/10m dipole", "grid": "IL38bp", "lat": 28.646, "lon": -13.905, "region": "Other", "snr": 34, "score": 1, "users_max": 50},
  {"url": "http://190.123.83.42:8073", "name": "LU1HCW-LW1HJP | ALPA CORRAL ARGENTINA", "loc": "ALPA CORRAL ARGENTINA", "antenna": "DIPOLO-20 40", "grid": "FF77oi", "lat": -32.66, "lon": -64.76, "region": "South America", "snr": 33, "score": 0, "users_max": 2},
  {"url": "http://hl5ntr.ddns.net:8074", "name": "0-30 MHz KIWI SDR( 4ch ), HL5NTR, Daegu_City Republic of Kor", "loc": "Dae_Gu City, South Korea", "antenna": "HF 85M Loop Antenna and 6M Band 6 Ele Yagi & 5/8 GP Antenna", "grid": "PM45HV02", "lat": 35.889, "lon": 128.575, "region": "Asia/Pacific", "snr": 32, "score": 5, "users_max": 8},
  {"url": "http://www.ecsykes.com:8073", "name": "10-30MHz SDR, KD2OM | Victor, New York", "loc": "Victor, New York", "antenna": "350 Foot Beverage", "grid": "FN12gx", "lat": 42.969, "lon": -77.427, "region": "North America", "snr": 32, "score": 3, "users_max": 4},
  {"url": "http://newbraunfels.proxy.kiwisdr.com", "name": "0-30 MHz SDR | New Braunfels, TX", "loc": "New Braunfels, TX", "antenna": "Loop On Ground", "grid": "EL09wq", "lat": 29.67, "lon": -98.12, "region": "North America", "snr": 31, "score": 2, "users_max": 3},
  {"url": "http://palomar-2.proxy.kiwisdr.com", "name": "K6VZK 0-30 MHZ KiwiSDR #2 | Palomar Moutain, CA", "loc": "Palomar Moutain, CA", "antenna": "IDAFAB / N1CL Designs Active Antenna", "grid": "DM13nh", "lat": 33.31, "lon": -116.85, "region": "North America", "snr": 31, "score": 1, "users_max": 1},
  {"url": "http://la6lutha.proxy.kiwisdr.com", "name": "LA6LU KiwiSDR - Cha-Am, Thailand (0-30 MHz SDR)", "loc": "Cha-Am, Thailand", "antenna": "NTi MegActiv MA305FT Active Wideband Antenna", "grid": "NK92xt", "lat": 12.79, "lon": 99.97, "region": "Asia/Pacific", "snr": 31, "score": 1, "users_max": 8},
  {"url": "http://greatlakesreceiver.hopto.me:8073", "name": "Great Lakes Online Receiver | Muskegon, Michigan USA", "loc": "Muskegon, Michigan USA", "antenna": "Shortwave Radio Active Loop Antenna", "grid": "EN63vf", "lat": 43.241, "lon": -86.225, "region": "North America", "snr": 30, "score": 3, "users_max": 4},
  {"url": "http://22545.proxy.kiwisdr.com", "name": "🟠VK3SOL-Strathbogie Rx1. Victoria, Australia [Vert. Loop. 0.", "loc": "Strathbogie, Victoria, Australia", "antenna": "Vertical Loop", "grid": "QF23ud", "lat": -36.853, "lon": 145.738, "region": "Asia/Pacific", "snr": 30, "score": 3, "users_max": 4},
  {"url": "http://ja5fp2.proxy.kiwisdr.com", "name": "JA5FP 40m | Chiba, Japan", "loc": "Chiba, Japan", "antenna": "EndFed", "grid": "QM05cq", "lat": 35.668, "lon": 140.172, "region": "Asia/Pacific", "snr": 30, "score": 0, "users_max": 4},
  {"url": "http://22200.proxy.kiwisdr.com", "name": "🍊🥭LU5LCR Paso de la Patria 🥭🍊", "loc": "Paso de la Patria", "antenna": "G5RV max. Extended to improve reception in MW", "grid": "GG02rq", "lat": -27.304, "lon": -58.554, "region": "South America", "snr": 29, "score": 1, "users_max": 4},
  {"url": "http://palomar-1.proxy.kiwisdr.com", "name": "K6VZK 0-30 MHZ KiwiSDR #1 | Palomar Moutain, CA", "loc": "Palomar Moutain, CA", "antenna": "IDAFAB / N1CL Designs Active Antenna", "grid": "DM13nh", "lat": 33.31, "lon": -116.85, "region": "North America", "snr": 29, "score": 1, "users_max": 2},
  {"url": "http://ve3hoa.ddns.net:8073", "name": "0-30 MHz SDR, VE3HOA | Ottawa, Canada", "loc": "Ottawa, Canada", "antenna": "160 meter Beverage", "grid": "FN15", "lat": 45.27, "lon": -76.05, "region": "North America", "snr": 27, "score": 3, "users_max": 4},
  {"url": "http://22561.proxy.kiwisdr.com", "name": "0-30 MHz SDR | Flores island,Azores,Portugal", "loc": "Flores island,Azores,Portugal", "antenna": "LZ1AQ MAG LOOP DAYS /TUNED LOOP 630M FROM 2200 TO 0730 UTC", "grid": "HM49KK", "lat": 39.445, "lon": -31.164, "region": "Other", "snr": 27, "score": 2, "users_max": 3},
  {"url": "http://cyp.twrmon.net:8073", "name": "0-30 MHz SDR | Cyprus", "loc": "Cyprus", "antenna": "Magnetic Loop Antenna", "grid": "KM64mq", "lat": 34.76, "lon": 32.53, "region": "Other", "snr": 23, "score": 2, "users_max": 7},
  {"url": "http://22235.proxy.kiwisdr.com", "name": "0-30 MHz KIWI SDR2 | Near Vinhedo SP - Brazil", "loc": "Near Vinhedo SP - Brazil", "antenna": "T3FD @20m agl", "grid": "GG66mx", "lat": -23.02, "lon": -46.99, "region": "South America", "snr": 22, "score": 0, "users_max": 4},
  {"url": "http://hk4rau.proxy.kiwisdr.com", "name": "HK4RAU SDR 0-30 MHz. | HK4RAU.", "loc": "HK4RAU.", "antenna": "DIPOLO", "grid": "FJ25", "lat": 5.675, "lon": -75.724, "region": "South America", "snr": 17, "score": 0, "users_max": 7},
  {"url": "http://22702.proxy.kiwisdr.com", "name": "0-30 MHz SDR | Goiania, Brazil", "loc": "Goiania, Brazil", "antenna": "Long-Wire 20mts", "grid": "GH53gf", "lat": -16.785, "lon": -49.493, "region": "South America", "snr": 17, "score": 0, "users_max": 3},
  {"url": "http://curacautin.bloap.cl", "name": "KiwiSDR Curacautín, Chile", "loc": "Curacautín, Araucanía, Chile", "antenna": "YAESU YA-30", "grid": "FF48", "lat": -38.433, "lon": -71.883, "region": "South America", "snr": 16, "score": 0, "users_max": 1},
  {"url": "http://lu4aa.proxy.kiwisdr.com", "name": "KiwiSDR del Radio Club Argentino (LU4AA) ubicado en el Insti", "loc": "Berazategui, Provincia de Buenos Aires, ", "antenna": "Random Wire", "grid": "GF05WD", "lat": -34.867, "lon": -58.14, "region": "South America", "snr": 16, "score": 0, "users_max": 3},
  {"url": "http://22560.proxy.kiwisdr.com", "name": "0-30 MHz SDR XQ4KTM | San Carlos, Chile", "loc": "San Carlos, Chile", "antenna": "Walmar MA1140", "grid": "FF43an", "lat": -36.427, "lon": -71.979, "region": "South America", "snr": 16, "score": 0, "users_max": 4},
  {"url": "http://76.53.60.62:8073", "name": "0-30 MHz SDR | Waimea, Hawaii", "loc": "Waimea, Hawaii", "antenna": "Tuned fan dipole", "grid": "BL20da", "lat": 20.031, "lon": -155.695, "region": "Other", "snr": 15, "score": 1, "users_max": 4},
  {"url": "http://ti0rc.proxy.kiwisdr.com", "name": "RADIOCLUB COSTA RICA | San Jose", "loc": "San Jose", "antenna": "TH-36", "grid": "EJ79xw", "lat": 9.921, "lon": -84.059, "region": "Other", "snr": 14, "score": 0, "users_max": 8},
  {"url": "http://alg.twrmon.net:8073", "name": "ZS2JB - KiwiSDR | Gqeberha, South Africa", "loc": "Gqeberha, South Africa", "antenna": "Wellbrook Magnetic Loop", "grid": "KF26ta", "lat": -33.98, "lon": 25.64, "region": "Other", "snr": 13, "score": 3, "users_max": 7},
  {"url": "http://jnb.twrmon.net:8073", "name": "TWR | Johannesburg", "loc": "Johannesburg", "antenna": "Wellbrook Magnetic Loop", "grid": "KG43cu", "lat": -26.13, "lon": 28.2, "region": "Other", "snr": 13, "score": 3, "users_max": 7},
  {"url": "http://sdr.cyhams.org", "name": "Cyprus Amateur Radio Society (0-30 MHZ SDR)", "loc": "Skourgiotissa, Cyprus", "antenna": "MLA-30 Plus MegaLoop 500 Khz - 30 Mhz", "grid": "KM65lc", "lat": 35.082, "lon": 32.912, "region": "Other", "snr": 13, "score": 2, "users_max": 8},
];

export const CATALOG_REGIONS = ["Any", "Europe", "North America", "Asia/Pacific", "South America", "Other"];
